
program: main.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  batch_size:
    distribution: int_uniform
    min: 1
    max: 4
  lr:
    distribution: log_uniform
    min: -10
    max: -3
  num_layers:
    distribution: int_uniform
    min: 2
    max: 6
  features_start:
    distribution: categorical
    values:
      - 8
      - 16
      - 32
      - 64
      - 128
  bilinear:
    distribution: categorical
    values:
      - True
      - False
  grad_batches:
    distribution: int_uniform
    min: 1
    max: 10